### ISSUE TITLE
When I click on latex equation, it shows me some default dummy.

### ISSUE THREAD

**Issue by aw3s0me** [OSCOSS/fiduswriter#21]
It must show the formula typed BEFORE
![image](https://cloud.githubusercontent.com/assets/3517287/13813549/7475a41c-eb82-11e5-815c-7f80fb3d9cd5.png)

**Comment by aw3s0me** [comment]
inside this event
jQuery(document).on('mousedown', '#button-math:not(.disabled), .equation', function (event) {
 editor.pm.selection.node; is undefined
That is why if (node && node.type && node.type.name === 'citation') { 
is unreachable.
However, pm.selection has head -> can get position

**Comment by johanneswilm** [comment]
Fixed upstream.

**Comment by aw3s0me** [comment]
MM. Seems it is not solved, pm.selection.node is still undefined + causing another bug

**Comment by johanneswilm** [comment]
True. What is fixed is if you select the node by navigating there with the keyboard. I have not looked into mouseclicking.

**Comment by aw3s0me** [comment]
Now the way to change formula - select it, and push again the button equation.
